name: Restrict Reviewers

on:
  pull_request:
    types: [opened, edited, review_requested]

jobs:
  check-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Set up GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      - name: Verify Code Owner Reviewers
        run: |
          CODEOWNERS_REVIEWERS=$(grep -v '^#' CODEOWNERS | awk '{print $NF}')
          NON_CODEOWNERS=$(gh pr view ${{ github.event.pull_request.number }} --json reviewers --jq '.reviewers[].login' | grep -vF "$CODEOWNERS_REVIEWERS" || true)
          
          if [ -n "$NON_CODEOWNERS" ]; then
            echo "Non-CodeOwner reviewers found: $NON_CODEOWNERS"
            echo "Removing non-CodeOwner reviewers..."
            for reviewer in $NON_CODEOWNERS; do
              gh pr reviewer remove ${{ github.event.pull_request.number }} --reviewer "$reviewer"
            done
          fi
      - name: Fail if unauthorized reviewers were present
        run: |
          if [ -n "$NON_CODEOWNERS" ]; then
            echo "Unauthorized reviewers detected and removed. Failing the check."
            exit 1
          fi
